apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    description: pod-nginx
    environment: nginx-environment
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80