apiVersion: v1
kind: Pod
metadata:
  name: nodejs
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - name: nodejs
    image: khannedy/nodejs-writer
    volumeMounts:
    - name: html
      mountPath: /app/html