apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replication
  labels:
    label: replica-set
  annotations:
    description: replication set test
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - prod
          - dev
  template:
    metadata:
      name: replication
      labels:
        app: nginx
        env: prod
    spec:
      containers:
        - name: rs-nginx
          image: nginx
          ports:
            - name: web
              containerPort: 80