apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
        - name: pod-jobs
          image: busybox
          command: ["echo", "hai des this is jobs"]
      restartPolicy: Never