apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replication
spec:
  replicas: 3
  selector:
    matchLabels:
      label: nginx
  template:
    metadata:
      name: srv-nginx
      labels:
        label: nginx
    spec:
      containers:
        - name: srv-nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    label: nginx
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - name: curl
    image: destiaeka/nginx-curl