apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-downward
data:
  APPLICATION: testing aja sih des
  DESCRIPTION: downward api

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-downward
spec:
  replicas: 2
  selector:
    matchLabels:
      name: downward
  template:
    metadata:
      labels:
        name: downward
    spec:
      containers:
      - name: nodejs
        image: khannedy/nodejs-env
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: cm-downward
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName

---


kind: Service
apiVersion: v1
metadata:
  name: service-downward
spec:
  type: NodePort
  selector:
    name: downward
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001